# 返回值和错误处理

## 可恢复错误Result
```rs
enum Result<T, E> {
    Ok(T),
    Err(E),
}
```
### 对返回错误进行处理
```rs
use std::fs::File;
use std::io::ErrorKind;

fn main() {
    let f = File::open("hello.txt");

    let f = match f {
        Ok(file) => file,
        Err(error) => match error.kind() {
            ErrorKind::NotFound => match File::create("hello.txt") {
                Ok(fc) => fc,
                Err(e) => panic!("Problem creating the file: {:?}", e),
            },
            other_error => panic!("Problem opening the file: {:?}", other_error),
        },
    };
}
```

### unwrap和expect
unwrap: 如果返回成功，就将 Ok(T) 中的值取出来，如果失败，就直接 panic
expect: panic时打印指定信息
```rs
let f = File::open("hello.txt").unwrap();
let f = File::open("hello.txt").expect("文件打开失败");
```

### 传播错误
```rs
use std::fs::File;
use std::io;
use std::io::Read;

fn read_username_from_file() -> Result<String, io::Error> {
    let mut s = String::new();

    File::open("hello.txt")?.read_to_string(&mut s)?;

    Ok(s)
}
```